apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: retail-prod
resources:
  - ../../base/namespace.yaml
  - ../../base/deployment.yaml
  - ../../base/service.yaml
  - ingress/ingress-basic-path.yaml
  - ingress/ingress-cors.yaml
  - ingress/ingress-gzip-compression.yaml
  - ingress/ingress-header-modification.yaml
  - ingress/ingress-host-only.yaml
  - ingress/ingress-ip-whitelist.yaml
  - ingress/ingress-method-restriction.yaml
  - ingress/ingress-multiple-backends.yaml
  - ingress/ingress-proxy-body-size.yaml
  - ingress/ingress-proxy-timeout.yaml
  - ingress/ingress-rate-limiting.yaml
  - ingress/ingress-rewrite-target.yaml
  - ingress/ingress-ssl-redirect.yaml
  - ingress/ingress-underscores-headers.yaml
  - ingress/ingress.yaml
