apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-class-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: class.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: class-service
                port:
                  number: 80
