apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: header-modification-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Tenant retail-prod;
      proxy_set_header X-Forwarded-Proto https;
      more_set_headers "X-Content-Type-Options: nosniff";
      more_clear_headers "X-Powered-By";
spec:
  rules:
    - host: headers.example.com
      http:
        paths:
          - path: /headers
            pathType: Prefix
            backend:
              service:
                name: header-service
                port:
                  number: 80
